import iPhone from "../Images/iPhone.png";
import Bag from "../Images/Bag.jpg";
import lehenga from "../Images/lehenga.jpg";
import lipstick from "../Images/lipstick.jpg";
import menShoes from "../Images/menShoes.jpg";
import oneplus from "../Images/oneplus.jpg";
import redshoes from "../Images/redshoes.jpg";
import washingMachine from "../Images/washingMachine.jpg";
import WaterBottle from "../Images/WaterBottle.jpg";

export  const productList =  [{
    id:1,
    picture: iPhone,
    product: "iPhone",
    rate: "$80.00 - $120.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {
    id:2,
    picture: Bag,
    product: "Bag",
    rate: "$20.00 - $30.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {   id:3,
    picture: lipstick,
    product: "LipStick",
    rate: "$30.00 - $50.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {   id:4,
    picture: washingMachine,
    product: "Washing Machine",
    rate: "$60.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:5,
    picture: menShoes,
    product: "Shoes",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:6,
    picture: oneplus,
    product: "HeadPhone",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:7,
    picture: redshoes,
    product: "Fancy Shoes",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},
{id:8,
    picture: lehenga,
    product: "Lehenga",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},
{id:9,
    picture: WaterBottle,
    product: "Water Bottle",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},{id:10,
    picture: iPhone,
    product: "iPhone",
    rate: "$80.00 - $120.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:11,
    picture: Bag,
    product: "Bag",
    rate: "$20.00 - $30.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:12,
    picture: lipstick,
    product: "LipStick",
    rate: "$30.00 - $50.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:13,
    picture: washingMachine,
    product: "Washing Machine",
    rate: "$60.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:14,
    picture: menShoes,
    product: "Shoes",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:15,
    picture: oneplus,
    product: "HeadPhone",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:16,
    picture: redshoes,
    product: "Fancy Shoes",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},
{id:17,
    picture: lehenga,
    product: "Lehenga",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},
{id:18,
    picture: WaterBottle,
    product: "Water Bottle",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},{id:19,
    picture: iPhone,
    product: "iPhone",
    rate: "$80.00 - $120.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:20,
    picture: Bag,
    product: "Bag",
    rate: "$20.00 - $30.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:21,
    picture: lipstick,
    product: "LipStick",
    rate: "$30.00 - $50.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:22,
    picture: washingMachine,
    product: "Washing Machine",
    rate: "$60.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:23,
    picture: menShoes,
    product: "Shoes",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:24,
    picture: oneplus,
    product: "HeadPhone",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:25,
    picture: redshoes,
    product: "Fancy Shoes",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},
{id:26,
    picture: lehenga,
    product: "Lehenga",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},
{id:27,
    picture: WaterBottle,
    product: "Water Bottle",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},{id:28,
    picture: iPhone,
    product: "iPhone",
    rate: "$80.00 - $120.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:29,
    picture: Bag,
    product: "Bag",
    rate: "$20.00 - $30.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:30,
    picture: lipstick,
    product: "LipStick",
    rate: "$30.00 - $50.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:31,
    picture: washingMachine,
    product: "Washing Machine",
    rate: "$60.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:32,
    picture: menShoes,
    product: "Shoes",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
}, {id:33,
    picture: oneplus,
    product: "HeadPhone",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "electronics"
}, {id:34,
    picture: redshoes,
    product: "Fancy Shoes",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},
{id:35,
    picture: lehenga,
    product: "Lehenga",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},
{id:36,
    picture: WaterBottle,
    product: "Water Bottle",
    rate: "$40.00 - $80.00",
    addCard:"Add To Card",
    buyNow:"Buy Now",
    categories: "fancyItems"
},
]